### ISSUE TITLE
Форматування

### ISSUE THREAD

**Issue by volodymyr-kushnir** [mistoso/bsa17js_git#3]
@mistoso, друга (**didactics.md**) просто агонь, але форматування залишає бажати кращого. Можна якось переноси порозставляти? Або, якщо це так має бути, то хоча б абзац з поясненням чому це так має бути (може віршовий розмір такий, я не в курсі) до нового файлу **README.md**? І заодно опис проекту/репозиторію в той же ж **README.md**.

P. S. Нам треба більше гілок, можна навіть **README.md** окремою гілкою залити. **Issues** можна закривати автоматично, якщо в повідмоленні комміту вписати **(fixes #3)**, наприклад, "Fixes #3: Add README.md" або "Added README.md (resolves #3)".

**Comment by mistoso** [comment]
Дякую за несподівану допомогу й підтримку, 
локально була створена гілка "fix-markdown" з комітом по виправленню форматування, що правда я забув вказати тег по закриттю issues.

**Comment by volodymyr-kushnir** [comment]
@mistoso та пофіг за тег, просто будеш мати на увазі шо тут таке є. То як пушнеш ті зміни, то закрий тоді цю проблему вручну.
І ще одне прохання пушити наверх частіше — я тут стикнувся щойно з ситуацією, коли все було змерджено локально і наверх була пушнута тільки гілка `master`, відтак на **GitHub**'і не було жодної згадки про інші гілки і довелось просити автора про `git reflog`. Це не є помилкою автора, це я просто криво умову завдання описав, не спрогнозував таку ситуацію, але раз вже зайшла тут така мова, то я б попросив пушити частіше. Воно додасть трохи роботи, бо буде просити вказати апстрім для кожної гілки, ну але це раптом 10 додаткових символів набрати...
